# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILsNRlUkyEMWeJMWpcVnSQRdupwnym1V
"""

<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Career Quiz | คุณเหมาะกับกน.ฝ่ายไหน</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;400;500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Kanit', sans-serif;
            /* พื้นหลังลาย Polka Dot */
            background-color: #fdfcfb;
            background-image: radial-gradient(#e5e7eb 0.8px, transparent 0.8px);
            background-size: 24px 24px;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 0;
            padding: 20px 0;
        }
        .quiz-card {
            backdrop-filter: blur(5px);
            background-color: rgba(255, 255, 255, 0.9);
            border: 1px solid rgba(255, 255, 255, 0.3);
        }
        .fade-in { animation: fadeIn 0.5s ease-in; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }

        /* สไตล์สำหรับตัวนับผู้เข้าชม */
        .counter-wrapper {
            margin-top: 40px;
            text-align: center;
            opacity: 0.7;
            font-size: 10px;
            letter-spacing: 0.1em;
            color: #94a3b8;
        }
    </style>
</head>
<body>

    <div id="quiz-container" class="max-w-xl w-full quiz-card rounded-[2rem] shadow-xl shadow-slate-200/50 p-8 md:p-12 fade-in mx-4">
        <!-- หน้าแรก (Start Screen) -->
        <div id="start-screen" class="text-center">
            <div class="inline-block p-3 bg-slate-100 rounded-full mb-4">✨</div>
            <h1 class="text-2xl font-medium text-slate-800 mb-4">ค้นหาสไตล์งานที่ใช่สำหรับคุณ</h1>
            <p class="text-slate-500 mb-8 text-sm">ตอบคำถาม 6 ข้อ เพื่อดูว่าตัวตนของคุณ<br>เหมาะกับสายงานประเภทไหน</p>
            <button onclick="startQuiz()" class="w-full bg-slate-800 text-white px-8 py-4 rounded-2xl hover:bg-slate-700 transition-all active:scale-95 font-light">เริ่มทำแบบทดสอบ</button>
        </div>

        <!-- หน้าคำถาม (Quiz Screen) -->
        <div id="quiz-screen" class="hidden">
            <div class="mb-8">
                <div class="flex justify-between items-center mb-2">
                    <span id="progress" class="text-[10px] font-medium text-slate-400 tracking-[0.2em] uppercase">Question 1/6</span>
                </div>
                <div class="w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
                    <div id="progress-bar" class="bg-slate-800 h-full transition-all duration-500" style="width: 16.6%"></div>
                </div>
            </div>
            <h2 id="question-text" class="text-lg text-slate-800 mb-8 font-normal leading-relaxed">คำถามจะปรากฏที่นี่</h2>
            <div id="options-container" class="space-y-3"></div>
        </div>

        <!-- หน้าผลลัพธ์ (Result Screen) -->
        <div id="result-screen" class="hidden text-center fade-in">
            <div class="mb-6">
                <span class="text-[10px] tracking-[0.3em] text-slate-400 uppercase">Your Result</span>
                <h1 id="result-title" class="text-3xl font-medium text-slate-800 mt-2 mb-4">สายงาน...</h1>
                <div class="h-1 w-12 bg-slate-800 mx-auto rounded-full mb-6"></div>
                <p id="result-desc" class="text-slate-500 mb-10 leading-relaxed text-sm px-4"></p>
            </div>
            <button onclick="location.reload()" class="text-slate-400 hover:text-slate-800 transition text-xs underline underline-offset-8">ลองทำใหม่อีกครั้ง</button>
        </div>
    </div>

    <!-- ส่วนที่นับจำนวนผู้เข้าชมที่คุณให้มา -->
    <div class="counter-wrapper fade-in">
        <p class="mb-2 uppercase">Visitor Count</p>
        <div class="flex flex-col items-center gap-1">
            <script type='text/javascript' src='https://www.freevisitorcounters.com/auth.php?id=b10194b50212017c3cf32fa956980d6f5f2bf3ea'></script>
            <script type="text/javascript" src="https://www.freevisitorcounters.com/en/home/counter/1544041/t/2"></script>
        </div>
    </div>

    <script>
        const questions = [
            { q: "1. ในช่วงเวลาว่าง คุณมักจะชอบทำอะไรมากที่สุด?", a: [
                { t: "วิเคราะห์ แก้ปัญหา หรือเล่นเกมวางแผน", type: "analyst" },
                { t: "วาดรูป ฟังเพลง หรือหาแรงบันดาลใจใหม่ๆ", type: "creative" },
                { t: "พูดคุย แลกเปลี่ยนความคิดเห็นกับผู้คน", type: "social" },
                { t: "จัดระเบียบของ หรือวางแผนตารางเวลา", type: "organizer" }
            ]},
            { q: "2. ถ้าต้องทำงานกลุ่ม คุณมักจะรับหน้าที่ไหน?", a: [
                { t: "คนหาข้อมูลและตรวจสอบความถูกต้อง", type: "analyst" },
                { t: "คนออกแบบสไลด์หรือพรีเซนต์ให้สวยงาม", type: "creative" },
                { t: "คนประสานงานและดูแลเพื่อนในทีม", type: "social" },
                { t: "คนคุมเวลาและสรุปขั้นตอนการทำงาน", type: "organizer" }
            ]},
            { q: "3. บรรยากาศการทำงานแบบไหนที่คุณใฝ่ฝัน?", a: [
                { t: "เงียบสงบ มีสมาธิ ใช้ความคิดได้เต็มที่", type: "analyst" },
                { t: "ยืดหยุ่น มีพื้นที่ให้ปล่อยของและไอเดีย", type: "creative" },
                { t: "ได้พบปะผู้คนใหม่ๆ ตลอดเวลา", type: "social" },
                { t: "เป็นระบบ ระเบียบ ทุกอย่างชัดเจน", type: "organizer" }
            ]},
            { q: "4. คุณจัดการกับปัญหาเฉพาะหน้าอย่างไร?", a: [
                { t: "หยุดคิด หาสาเหตุ แล้วค่อยๆ แก้ตามตรรกะ", type: "analyst" },
                { t: "หาทางออกใหม่ๆ ที่ไม่ซ้ำใคร", type: "creative" },
                { t: "ขอความช่วยเหลือหรือปรึกษาคนรอบข้าง", type: "social" },
                { t: "ดูตามขั้นตอนหรือกฎที่มีไว้", type: "organizer" }
            ]},
            { q: "5. สิ่งไหนที่คุณให้ความสำคัญที่สุดในการทำงาน?", a: [
                { t: "ความถูกต้องและแม่นยำ", type: "analyst" },
                { t: "เอกลักษณ์และความแปลกใหม่", type: "creative" },
                { t: "การสร้างความพึงพอใจให้ผู้คน", type: "social" },
                { t: "ประสิทธิภาพและความรวดเร็ว", type: "organizer" }
            ]},
            { q: "6. วิชาที่คุณรู้สึกว่าเป็นตัวเองที่สุดเมื่อได้เรียน?", a: [
                { t: "วิทยาศาสตร์ หรือ คณิตศาสตร์", type: "analyst" },
                { t: "ศิลปะ หรือ ภาษา", type: "creative" },
                { t: "สังคมศาสตร์ หรือ จิตวิทยา", type: "social" },
                { t: "บริหารจัดการ หรือ การจัดการข้อมูล", type: "organizer" }
            ]}
        ];

        const results = {
            analyst: { title: "The Analyst", desc: "คุณคือยอดนักคิด! คุณชอบงานที่ต้องใช้ตรรกะ การวิเคราะห์ และการแก้ไขปัญหาที่ซับซ้อน เช่น สายวิทยาศาสตร์, IT หรือการวิเคราะห์ข้อมูล" },
            creative: { title: "The Creative", desc: "จินตนาการของคุณไม่มีที่สิ้นสุด! คุณเหมาะกับงานที่ได้แสดงออกถึงความคิดสร้างสรรค์ เช่น งานดีไซน์, โฆษณา หรือศิลปะทุกแขนง" },
            social: { title: "The Socializer", desc: "พลังของคุณมาจากการพูดคุย! คุณเก่งเรื่องการทำความเข้าใจผู้คน เหมาะกับสายงานประชาสัมพันธ์, HR, หรือนักจิตวิทยา" },
            organizer: { title: "The Organizer", desc: "ระเบียบวินัยคือหัวใจของคุณ! คุณจัดการทุกอย่างได้อย่างแม่นยำ เหมาะกับงานบริหารจัดการ หรือนักวางแผนระบบ" },
            versatile: { title: "The Multitasker", desc: "คุณมีความสามารถที่หลากหลายและปรับตัวเก่งมาก เหมาะกับงานบริหารโปรเจกต์หรือเจ้าของธุรกิจ" }
        };

        let currentStep = 0;
        let scores = { analyst: 0, creative: 0, social: 0, organizer: 0 };

        function startQuiz() {
            document.getElementById('start-screen').classList.add('hidden');
            document.getElementById('quiz-screen').classList.remove('hidden');
            showQuestion();
        }

        function showQuestion() {
            const q = questions[currentStep];
            document.getElementById('question-text').innerText = q.q;
            document.getElementById('progress').innerText = `Question ${currentStep + 1}/6`;
            document.getElementById('progress-bar').style.width = `${((currentStep + 1) / 6) * 100}%`;

            const container = document.getElementById('options-container');
            container.innerHTML = '';
            q.a.forEach(opt => {
                const btn = document.createElement('button');
                btn.className = "w-full text-left p-4 border border-slate-100 rounded-2xl hover:border-slate-800 hover:bg-slate-50 transition-all duration-200 text-slate-600 text-sm font-light active:scale-[0.98]";
                btn.innerText = opt.t;
                btn.onclick = () => nextStep(opt.type);
                container.appendChild(btn);
            });
        }

        function nextStep(type) {
            scores[type]++;
            currentStep++;
            if (currentStep < questions.length) {
                showQuestion();
            } else {
                showResult();
            }
        }

        function showResult() {
            document.getElementById('quiz-screen').classList.add('hidden');
            document.getElementById('result-screen').classList.remove('hidden');

            let maxScore = 0;
            let resultType = '';

            for (const key in scores) {
                if (scores[key] > maxScore) {
                    maxScore = scores[key];
                    resultType = key;
                }
            }

            const countMax = Object.values(scores).filter(v => v === maxScore).length;
            if (countMax > 1) resultType = 'versatile';

            document.getElementById('result-title').innerText = results[resultType].title;
            document.getElementById('result-desc').innerText = results[resultType].desc;
        }
    </script>
</body>
</html>

html::before {
  content: 'CodePen ♥ The Web';
  position: fixed;
  inset: 0;
  z-index: -1;
  margin: auto;
  width: fit-content;
  height: fit-content;
  font-family: monospace;
  opacity: 0.6;
  background: rebeccapurple;
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
}